# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes


[general]
# cyber_punk_neon, challenger_deep,tomorrow_night_bright, iterm
import = ["~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"]

[window]
padding = { x = 5, y = 2 }
opacity = 0.85
blur = false
startup_mode = "Maximized"
decorations = "None"

[cursor]
style = "Beam"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 13.5
offset = { x = 0, y = 4}

# brew install --cask font-jetbrains-mono-nerd-font

[font.normal]
#family = "JetBrainsMono Nerd Font"
family  = "0xProto"
# style = "Regular"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "Return", mods = "Command", chars = "\u001b[34~" },
]

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "exec ~/.config/alacritty/start_tmux.sh"] }
